from typing import Annotated, Dict, List, TypedDict, Any
import operator

class AssemblyInfo(TypedDict):
    assembly_id: str
    rating: str
    description: str
    source_sheet: str
    components: List[str]

class DeficiencyFlag(TypedDict):
    level: str  # "CRITICAL", "WARNING", "NOTE"
    category: str # "Adjacency", "Under-design", "Missing Spec"
    description: str
    location: str
    recommendation: str

class ReportState(TypedDict):
    # ── Shared Knowledge (Tool E) ──
    # Using operator.setitem to allow subagents to update keys
    ledger: Annotated[Dict[str, AssemblyInfo], operator.ior]
    
    # ── Report Content ──
    # Each key is a section (e.g., "Executive Summary", "Wall Partitions")
    # Values are the Markdown content generated by subagents
    sections: Annotated[Dict[str, str], operator.ior]
    
    # ── Tracking ──
    deficiencies: Annotated[List[DeficiencyFlag], operator.add]
    completed_steps: Annotated[List[str], operator.add]
    
    # ── Context ──
    project_id: str
    revision_label: str
    document_map: Dict[str, Any]
    
    # ── Current Focus ──
    # The current task assigned by the Boss Agent
    current_task: str
    next_agent: str
